core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grade_system.urls', namespace='grade_system')),
]

core/grade_system/urls.py
from django.urls import path
from . import views

app_name = 'grade_system'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('teacher_dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('accountant_dashboard/', views.accountant_dashboard, name='accountant_dashboard'),
    path('group/<int:pk>/', views.group_detail, name='group_detail'),
    path('', views.main_page, name='main_page'),
    path('technologies_stack/', views.technologies_stack, name='technologies_stack'),
    path('accountant/calculate_coefficients/', views.calculate_coefficients, name='calculate_coefficients'),
    path('accountant/calculate_scholarship/', views.calculate_scholarship, name='calculate_scholarship'),
]

core/templates/main_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}My Site{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/grade_system.css' %}">
</head>
<body>
    <div class="header">
        <h1 class="logo">Добро пожаловать на мой сайт!</h1>
        <div class="navbar">
            <a href="{% url 'grade_system:login' %}"><i class="fas fa-home"></i>Войти</a>
            <a href="{% url 'grade_system:technologies_stack' %}"><i class="fas fa-graduation-cap"></i>Стек технологий</a>
        </div>
    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="content">
        {% block content %}{% endblock %}
    </div>

</body>
</html>