core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grade_system.urls', namespace='grade_system')),
]

core/grade_system/urls.py
from django.urls import path
from . import views

app_name = 'grade_system'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('teacher_dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('accountant_dashboard/', views.accountant_dashboard, name='accountant_dashboard'),
    path('group/<int:pk>/', views.group_detail, name='group_detail'),
    path('', views.main_page, name='main_page'),
    path('technologies_stack/', views.technologies_stack, name='technologies_stack'),
    path('accountant/calculate_coefficients/', views.calculate_coefficients, name='calculate_coefficients'),
    path('accountant/calculate_scholarship/', views.calculate_scholarship, name='calculate_scholarship'),
]

core/grade_system/models.py
from django.db import models
from django.db.models import OneToOneField
from django.conf import settings


class Accountant(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'accountant'

    def __str__(self):
        return f'{self.full_name}'


class Teacher(models.Model):
    user = OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'teacher'

    def __str__(self):
        return f'{self.full_name}'


class Speciality(models.Model):

    class Status(models.TextChoices):
        PR = 'ПР', 'Программная инженерия'
        PI = 'ПИ', 'Прикладная информатика'
        IV = 'ИВ', 'Информатика и вычислительная техника'
        IB = 'ИБ', 'Информационная безопасность'
        US = 'УС', 'Управление в технических системах'
        KB = 'КБ', 'Компьютерная безопасность'
        AS = 'АС', 'Безопасность автоматизированных систем'

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=2, choices=Status.choices)
    code = models.CharField(max_length=10)
    year = models.PositiveIntegerField()

    class Meta:
        db_table = 'speciality'
        unique_together = ['name', 'year']

    def __str__(self):
        return f'{self.name}, {self.year}'


class Discipline(models.Model):

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    is_credit = models.BooleanField(default=False)

    class Meta:
        db_table = 'discipline'

    def __str__(self):
        return f'{self.title}'


class Group(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20, unique=True)
    semester = models.IntegerField(default=1)
    speciality = models.ForeignKey(Speciality, on_delete=models.CASCADE)

    class Meta:
        db_table = 'group'

    def __str__(self):
        return self.name


class Student(models.Model):

    id = models.CharField(max_length=25, primary_key=True, unique=True, editable=False)
    name = models.CharField(max_length=100)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    scholarship_coefficient = models.FloatField(default=1.0)
    scholarship = models.FloatField(default=0.0)

    class Meta:
        db_table = 'student'

    def save(self, *args, **kwargs):
        if not self.id:
            self.id = self.generate_id()
        super().save(*args, **kwargs)

    def generate_id(self):
        last_student = Student.objects.filter(group=self.group).order_by('-id').first()

        if last_student:
            last_id = int(last_student.id.split('-')[-1])
            new_id = last_id + 1
        else:
            new_id = 1

        return f'{self.group}-{new_id}'

    def __str__(self):
        return f'{self.id}, {self.name}'


class Speciality_Discipline(models.Model):

    id = models.AutoField(primary_key=True)
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    semester = models.PositiveSmallIntegerField()
    active = models.BooleanField(default=False)
    speciality = models.ForeignKey(Speciality, on_delete=models.CASCADE)

    class Meta:
        db_table = 'speciality_discipline'

    def __str__(self):
        return f'{self.discipline}, {self.speciality}'


class Teacher_Discipline(models.Model):

    id = models.AutoField(primary_key=True)
    speciality_discipline = models.ForeignKey(Speciality_Discipline, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    class Meta:
        db_table = 'teacher_discipline'

    def __str__(self):
        return f'{self.speciality_discipline}'


class Grade(models.Model):

    id = models.AutoField(primary_key=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    teacher_discipline = models.ForeignKey(Teacher_Discipline, on_delete=models.CASCADE)
    score = models.PositiveSmallIntegerField(null=True, blank=True)

    class Meta:
        db_table = 'grade'

    def is_passed(self):
        return self.score == 5

    def __str__(self):
        return f'{self.score}'

core/grade_system/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

core/grade_system/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch, Subquery, FloatField
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_protect
from .forms import LoginForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .models import Teacher, Discipline, Group, Student, Grade, Teacher_Discipline, Accountant


def get_teacher_disciplines(teacher):
    disciplines = Discipline.objects.filter(
        speciality_discipline__teacher_discipline__teacher=teacher
    ).distinct()
    return disciplines


def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # Проверка, является ли пользователь преподавателем
                    try:
                        teacher = Teacher.objects.get(user=user)
                        disciplines = list(get_teacher_disciplines(teacher))
                        # Сохранение дисциплин в сессии
                        request.session['disciplines'] = [discipline.id for discipline in disciplines]
                        # Перенаправление на панель преподавателя
                        return redirect('grade_system:teacher_dashboard')
                    except Teacher.DoesNotExist:
                        pass

                    # Проверка, является ли пользователь бухгалтером
                    try:
                        accountant = Accountant.objects.get(user=user)
                        # Перенаправление на панель бухгалтера
                        return redirect('grade_system:accountant_dashboard')
                    except Accountant.DoesNotExist:
                        return HttpResponse('Вы не являетесь преподавателем или бухгалтером!')
                else:
                    return HttpResponse('Ваша запись отключена!')
            else:
                return HttpResponse('Недопустим вход!')
    else:
        form = LoginForm()
    return render(request, 'grade_system/login_form.html', {'form': form})


def get_groups_for_discipline(discipline):
    return Group.objects.filter(speciality__speciality_discipline__discipline=discipline).distinct()


@login_required
def teacher_dashboard(request):
    discipline_ids = request.session.get('disciplines', [])
    disciplines = Discipline.objects.filter(id__in=discipline_ids)

    disciplines_with_groups = []
    for discipline in disciplines:
        groups = get_groups_for_discipline(discipline)
        disciplines_with_groups.append({
            'discipline': discipline,
            'groups': groups
        })

    return render(request, 'grade_system/teacher_dashboard.html', {'disciplines_with_groups': disciplines_with_groups})


@login_required
def accountant_dashboard(request):
    students = Student.objects.all()  # Получение всех студентов, замените эту строку на ваш код получения студентов из базы данных
    return render(request, 'grade_system/accountant_dashboard.html', {'students': students})


@login_required
def group_detail(request, pk):
    group = get_object_or_404(Group, pk=pk)
    discipline_id = request.GET.get('discipline_id')
    discipline = get_object_or_404(Discipline, pk=discipline_id)

    if request.method == 'POST':
        for student in Student.objects.filter(group=group):
            if discipline.is_credit:
                is_passed = request.POST.get(f'grade_{student.id}') == 'on'
                grade_value = 5 if is_passed else None
            else:
                grade_value = request.POST.get(f'grade_{student.id}')
                if grade_value:
                    grade_value = int(grade_value)
                else:
                    grade_value = 0

            teacher_discipline = Teacher_Discipline.objects.get(
                speciality_discipline__discipline=discipline,
                speciality_discipline__speciality=group.speciality
            )
            Grade.objects.update_or_create(
                student=student,
                teacher_discipline=teacher_discipline,
                defaults={'score': grade_value}
            )
        messages.success(request, 'Оценки успешно обновлены!')
        # return redirect('grade_system:group_detail', pk=pk)

    students = Student.objects.filter(group=group).prefetch_related(
        Prefetch('grade_set', queryset=Grade.objects.filter(teacher_discipline__speciality_discipline__discipline=discipline))
    )

    student_grades = []
    for student in students:
        grade = student.grade_set.filter(teacher_discipline__speciality_discipline__discipline=discipline).first()
        student_grades.append({
            'student': student,
            'grade': grade,
            'is_passed': grade.is_passed() if grade else False
        })

    return render(request, 'grade_system/group_detail.html', {
        'group': group,
        'discipline': discipline,
        'students': student_grades
    })


def main_page(request):
    return render(request, 'grade_system/main.html')


def technologies_stack(request):
    return render(request, 'grade_system/technologies_stack.html')


@csrf_protect
def calculate_coefficients(request):
    if request.method == 'POST':
        students = Student.objects.all()
        for student in students:
            grades = Grade.objects.filter(student=student)
            all_grades_five = all(grade.score == 5 for grade in grades)
            has_grade_four = any(grade.score == 4 for grade in grades)
            has_grade_three = any(grade.score == 3 for grade in grades)
            if all_grades_five:
                student.scholarship_coefficient = 1.5
            elif has_grade_four and not has_grade_three:
                student.scholarship_coefficient = 1
            else:
                student.scholarship_coefficient = 0

            student.save()

    return redirect('grade_system:accountant_dashboard')


@csrf_protect
def calculate_scholarship(request):
    if request.method == 'POST':
        base_scholarship = float(request.POST.get('base_scholarship'))
        for student in Student.objects.all():
            student.scholarship = base_scholarship * student.scholarship_coefficient
            student.save()
        return redirect('grade_system:accountant_dashboard')

core/templates/grade_system/accountant_dashboard.html
{% extends "main_base.html" %}

{% block content %}
    <div class="dashboard-container">
        <h1>Бухгалтерская панель</h1>

        <!-- Форма для расчета коэффициентов стипендий -->
        <form method="post" action="{% url 'grade_system:calculate_coefficients' %}">
            {% csrf_token %}
            <button type="submit" class="btn-submit">Рассчитать коэффициенты</button>
        </form>

        <!-- Форма для ввода базовой стипендии и расчета итоговой стипендии -->
        <form method="post" action="{% url 'grade_system:calculate_scholarship' %}">
            {% csrf_token %}
            <label for="base_scholarship">Базовая стипендия (руб):</label>
            <input type="number" class="base_scholarship" name="base_scholarship">
            <button type="submit" class="btn-submit">Рассчитать стипендию</button>
        </form>

        <table>
            <thead>
                <tr>
                    <th>Студент</th>
                    <th>Группа</th>
                    <th>Коэффициент стипендии</th>
                    <th>Стипендия</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                    <tr>
                        <td>{{ student.name }}</td>
                        <td>{{ student.group.name }}</td>
                        <td>{{ student.scholarship_coefficient }}</td>
                        <td>{{ student.scholarship }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block extra_css %}
<style>
    .base_scholarship {
    width: 100%;
    padding: 10px;
    margin: 10px 0;
    border: 1px solid #ddd;
    border-radius: 4px;
    box-sizing: border-box;
}
</style>
{% endblock %}

core/templates/grade_system/group_detail.html
{% extends "main_base.html" %}

{% block title %}Выставление оценок{% endblock %}

{% block content %}
<div class="grade-container">
    <h2>Успеваемость</h2>
    <form method="POST">
        {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <th>Группа</th>
                    <th>Дисциплина</th>
                    <th>Студент</th>
                    {% if discipline.is_credit %}
                        <th>Зачет</th>
                    {% else %}
                        <th>Оценка</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for item in students %}
                    <tr>
                        <td>{{ group.name }}</td>
                        <td>{{ discipline.title }}</td>
                        <td>{{ item.student.name }}</td>
                        <td>
                            {% if discipline.is_credit %}
                                <input type="checkbox" name="grade_{{ item.student.id }}" {% if item.is_passed %}checked{% endif %} class="grade-input">
                            {% else %}
                                <input type="text" name="grade_{{ item.student.id }}" value="{{ item.grade.score }}" width=50px>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn-submit">Сохранить изменения</button>
    </form>
    <a href="{% url 'grade_system:teacher_dashboard' %}" class="btn-back">Назад к панели преподавателя</a>
</div>
{% endblock %}

core/templates/grade_system/login_form.html
{% extends "main_base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}
<div class="login-container">
    <h2>Вход в систему</h2>
    <p>Заполните форму, чтобы войти в систему:</p>
    <form method="post" class="login-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn-login">Войти</button>
    </form>
</div>
{% endblock %}

core/templates/grade_system/main.html
{% extends "main_base.html" %}

core/templates/grade_system/teacher_dashboard.html
{% extends "main_base.html" %}

{% block content %}
    <div class="dashboard-container">
        <h1>Преподавательская панель</h1>
        <ul class="discipline-list">
            {% for item in disciplines_with_groups %}
                <li class="discipline-item">
                    <div class="discipline-title">{{ item.discipline.title }}</div>
                    <ul class="group-list">
                        {% for group in item.groups %}
                            <li class="group-item">
                                <a href="{% url 'grade_system:group_detail' group.id %}?discipline_id={{ item.discipline.id }}" class="group-link">
                                    {{ group.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

core/templates/grade_system/technologies_stack.html
{% extends "main_base.html" %}

{% block content %}
    <div class="skills-container">
        <p>Привет! Я Васильев Семен Дмитриевич, студент 2 курса КубГТУ. Я разработал этот сайт как систему выставления оценок и расчета стипендии.</p>
        <ul class="skills-list">
            <li class="skill-item">
                <p>Django</p>
                <p>Фреймворк для создания веб-приложений на языке Python.</p>
            </li>
            <li class="skill-item">
                <p>REST API</p>
                <p>Архитектурный стиль взаимодействия компонентов распределенного приложения в сети.</p>
            </li>
            <li class="skill-item">
                <p>HTML + CSS</p>
                <p>Языки разметки и стилей для создания и оформления веб-страниц.</p>
            </li>
            <li class="skill-item">
                <p>SQLite</p>
                <p>Встроенная система управления базами данных, обеспечивающая легкость использования и настройки.</p>
            </li>
            <li class="skill-item">
                <p>Git</p>
                <p>Система контроля версий, обеспечивающая отслеживание изменений в коде и совместную работу разработчиков.</p>
            </li>
        </ul>
    </div>
{% endblock %}